#+TITLE: org-team

[[https://img.shields.io/github/v/tag/lepisma/org-team.svg?style=flat-square]]

My team management tooling in org mode. Features are added when I need them.
There is no long term plan or overarching vision here. You might still see
versions tags though.

Notes on the workflow follow.

** Workflow
Each person gets mapped to a local directory with certain structure (still in
flux) in place. They also get an equivalent cloud directory where we keep shared
content.

*** Inventory
...

*** 1:1s
...

**** Continuous logging
For feedback discussions, it's important to keep logging situations when they
occur. I use the following capture template that asks for the person's name,
then logs an entry with timestamp:

#+begin_src emacs-lisp
  (setq org-capture-templates
      ("t" "Team log" item (function org-team-visit-person-log)
             "- %U %?" :prepend t))
#+end_src

In the text, I usually write a small phrase pointing to the general area of note
like ~ownership~. Then I log the situation with sufficient details, links, etc.
Next few sentences specify my views, positive or negative, on the situation
which are followed up by the best thing that could have been done in that
situation.

The last bit about writing /the best thing/ to do derives from the /What "killing
it" would look like/' idea from [[https://review.firstround.com/the-power-of-performance-reviews-use-this-system-to-become-a-better-manager][Lenny's notes]]. and [[https://github.com/Vernacular-ai/handbook/blob/master/values.md#strive-for-excellence][our value Strive for
Excellence]].

*** Reminders
...

*** Surveying and monitoring
...

*** Dashboard
...
